import {describe,expect,it} from 'vitest';
import {RefinementAdjustmentEngine,type AdjustmentModelAdapter} from '../electron/refinement-adjustments';
import type {PrdProject,SourceUnit} from '../src/types';

const unit=(id:string,text:string):SourceUnit=>({id,label:id,kind:'paragraph',excerpt:text,location:id,status:'processed'});
const project=():PrdProject=>({id:'P',name:'PRD',sourceName:'prd.md',sourceHash:'H',revision:1,importedAt:'now',rawText:'',stage:'review',sourceUnits:[unit('S1','用户可以提交订单。'),unit('S2','用户可以取消订单。')],features:[{id:'F1',name:'提交订单',sourceUnitIds:['S1'],sourceRefs:[{sourceUnitId:'S1'}],ruleIds:[],requirementIds:['R1'],state:'reviewed'},{id:'F2',name:'取消订单',sourceUnitIds:['S2'],sourceRefs:[{sourceUnitId:'S2'}],ruleIds:[],requirementIds:['R2'],state:'reviewed'}],requirements:[{id:'R1',title:'提交',behavior:'用户可以提交订单',conditions:[],constraints:[],explicitAcceptanceConditions:[],sourceUnitIds:['S1'],evidenceBindings:{behavior:[{sourceUnitId:'S1'}],conditions:[],constraints:[],explicitAcceptanceConditions:[]},ruleIds:[],state:'reviewed'},{id:'R2',title:'取消',behavior:'用户可以取消订单',conditions:[],constraints:[],explicitAcceptanceConditions:[],sourceUnitIds:['S2'],evidenceBindings:{behavior:[{sourceUnitId:'S2'}],conditions:[],constraints:[],explicitAcceptanceConditions:[]},ruleIds:[],state:'reviewed'}],clarifications:[{id:'Q1',question:'是否允许重复提交？',reason:'原文未说明',affectedIds:['R1'],state:'open'}]});
const requirement=(input:any,id:string,behavior:string)=>{const evidence=input.evidenceCatalog.find((item:any)=>item.text.includes(behavior))??input.evidenceCatalog.find((item:any)=>item.sourceUnitId==='S1');return{id,title:behavior,behavior,conditions:[],constraints:[],explicitAcceptanceEvidenceIds:[],sourceUnitIds:[evidence.sourceUnitId],evidenceBindings:{behavior:[evidence.id],conditions:[],constraints:[],explicitAcceptanceConditions:[]},state:'reviewed'}};
const actions=(input:any,behavior='用户可以提交订单',extra:any={})=>({requirementActions:[{action:'update',targetId:'R1',requirement:requirement(input,'IGNORED',behavior)}],clarificationActions:[],relationActions:[],...extra});
const passed=(resolutions:any[]=[])=>(()=>({passed:true,issues:[],clarificationResolutions:resolutions}));
const adapter=(fn:(call:Parameters<AdjustmentModelAdapter['generate']>[0])=>unknown):AdjustmentModelAdapter=>({generate:async call=>fn(call)});
const normalAdapter=(make:(input:any)=>unknown):AdjustmentModelAdapter=>adapter(call=>call.title.includes('依据核查')?passed()():make(call.input));
const request=(values:Partial<any>={})=>({kind:'feature',baseTaskId:'T',baseVersion:1,featureId:'F1',instruction:'展开细化',scope:'feature',...values} as const);

describe('局部需求调整引擎',()=>{
  it('显式 update 保留正式编号且不改动其他功能',async()=>{const base=project(),engine=new RefinementAdjustmentEngine(normalAdapter(input=>actions(input)));const run=await engine.run({taskId:'T',version:1,project:base},request());expect(run.status).toBe('completed');expect(run.project.requirements.find(r=>r.id==='R1')?.behavior).toBe('用户可以提交订单');expect(run.project.requirements.find(r=>r.id==='R2')).toEqual(base.requirements[1]);expect(run.project.features.find(f=>f.id==='F2')).toEqual(base.features[1]);});

  it('无依据的 999 元手续费即使引用真实原文也会被语义复核拒绝，且最多修正一次',async()=>{let generationCalls=0,auditCalls=0;const engine=new RefinementAdjustmentEngine(adapter(call=>{if(call.title.includes('依据核查')){auditCalls++;return{passed:false,issues:['原文没有 999 元手续费'],clarificationResolutions:[]}}generationCalls++;const input=(call.input as any).evidenceCatalog?(call.input as any):(call.input as any).originalInput;return actions(input,'用户可以提交订单。需收取999元手续费')}));const run=await engine.run({taskId:'T',version:1,project:project()},request());expect(run.status).toBe('failed');expect(run.error).toContain('999 元手续费');expect(generationCalls).toBe(2);expect(auditCalls).toBe(2);expect(run.project).toEqual(project());});

  it('粒度指令不能被绑定为业务事实',async()=>{const engine=new RefinementAdjustmentEngine(normalAdapter(input=>actions(input,'展开细化')));const run=await engine.run({taskId:'T',version:1,project:project()},request());expect(run.status).toBe('failed');expect(run.error).toContain('粒度调整指令不能作为业务事实依据');});

  it('答案被需求承接并经语义复核确认后才解决澄清',async()=>{const engine=new RefinementAdjustmentEngine(adapter(call=>{if(call.title.includes('依据核查'))return passed([{clarificationId:'Q1',status:'supported',reason:'需求已引用用户答案'}])();const input=call.input as any,user=input.evidenceCatalog.find((item:any)=>item.sourceUnitId.startsWith('USER-'));return actions(input,'允许重复提交',{clarificationActions:[{action:'resolve',targetId:'Q1',satisfiedRequirementIds:['R1'],resolutionEvidenceIds:[user.sourceUnitId]}]})}));const run=await engine.run({taskId:'T',version:1,project:project()},request({kind:'clarification',clarificationId:'Q1',clarificationDisposition:'answered',featureId:undefined,instruction:'允许重复提交'}));expect(run.status).toBe('completed');expect(run.project.clarifications.find(q=>q.id==='Q1')?.state).toBe('resolved');expect(run.project.requirements.find(r=>r.id==='R1')?.sourceUnitIds).toContain(run.userEvidence.id);});

  it('答案未落实时不能因生成成功销账',async()=>{const engine=new RefinementAdjustmentEngine(adapter(call=>{if(call.title.includes('依据核查'))return{passed:false,issues:['需求没有承接答案'],clarificationResolutions:[{clarificationId:'Q1',status:'unsupported',reason:'仍只有原 PRD 行为'}]};const input=(call.input as any).evidenceCatalog?(call.input as any):(call.input as any).originalInput,user=input.evidenceCatalog.find((item:any)=>item.sourceUnitId.startsWith('USER-'));return actions(input,'用户可以提交订单',{clarificationActions:[{action:'resolve',targetId:'Q1',satisfiedRequirementIds:['R1'],resolutionEvidenceIds:[user.sourceUnitId]}]})}));const run=await engine.run({taskId:'T',version:1,project:project()},request({kind:'clarification',clarificationId:'Q1',clarificationDisposition:'answered',featureId:undefined,instruction:'允许重复提交'}));expect(run.status).toBe('failed');expect(run.error).toContain('没有承接答案');expect(run.project.clarifications[0].state).toBe('open');});

  it('普通粒度调整未显式处理澄清时保留原问题',async()=>{const engine=new RefinementAdjustmentEngine(normalAdapter(input=>actions(input)));const run=await engine.run({taskId:'T',version:1,project:project()},request());expect(run.status).toBe('completed');expect(run.project.clarifications).toEqual(project().clarifications);});

  it('删除需求导致澄清悬空时拒绝候选',async()=>{const engine=new RefinementAdjustmentEngine(normalAdapter(()=>({requirementActions:[{action:'delete',targetId:'R1'}],clarificationActions:[],relationActions:[]})));const run=await engine.run({taskId:'T',version:1,project:project()},request());expect(run.status).toBe('failed');expect(run.error).toContain('悬空澄清引用');});

  it('删除需求但未显式处理关系时拒绝候选',async()=>{const base=project();base.clarifications=[];base.relations=[{id:'REL1',sourceRequirementId:'R1',targetRequirementId:'R2',kind:'affects',sourceRefs:[{sourceUnitId:'S1'}]}];const engine=new RefinementAdjustmentEngine(normalAdapter(()=>({requirementActions:[{action:'delete',targetId:'R1'}],clarificationActions:[],relationActions:[]})));const run=await engine.run({taskId:'T',version:1,project:base},request());expect(run.status).toBe('failed');expect(run.error).toContain('relations[0]');});

  it('create 分配新编号而 update 不依赖数组位置',async()=>{const engine=new RefinementAdjustmentEngine(normalAdapter(input=>({requirementActions:[{action:'create',requirement:requirement(input,'LOCAL-NEW','用户可以提交订单')},{action:'update',targetId:'R1',requirement:requirement(input,'LOCAL-OLD','用户可以提交订单')}],clarificationActions:[],relationActions:[]})));const run=await engine.run({taskId:'T',version:1,project:project()},request());expect(run.status).toBe('completed');expect(run.project.features[0].requirementIds).toContain('R1');expect(run.project.features[0].requirementIds.some(id=>id.startsWith('R-ADJ-'))).toBe(true);});

  it('重生成失败时保留答案记录和原项目中的开放澄清',async()=>{const base=project(),engine=new RefinementAdjustmentEngine(adapter(()=>{throw new Error('模型失败')}));const run=await engine.run({taskId:'T',version:1,project:base},request({kind:'clarification',clarificationId:'Q1',clarificationDisposition:'answered',featureId:undefined,instruction:'允许重复提交'}));expect(run.status).toBe('failed');expect(run.userEvidence.content).toBe('允许重复提交');expect(run.project).toEqual(base);});

  it('拒绝从过期版本提交调整',async()=>{const engine=new RefinementAdjustmentEngine(adapter(()=>({})));await expect(engine.run({taskId:'T',version:2,project:project()},request())).rejects.toThrow('结果版本已变化');});
  it('全量补充只建立完整重生成路由，不调用局部模型',async()=>{let calls=0;const engine=new RefinementAdjustmentEngine(adapter(()=>{calls++;return{}}));const run=await engine.run({taskId:'T',version:1,project:project()},request({kind:'supplement',scope:'all',featureId:undefined,instruction:'订单需要记录渠道'}));expect(run.status).toBe('full-regeneration-required');expect(run.project.sourceUnits.some(unit=>unit.id===run.userEvidence.id)).toBe(true);expect(calls).toBe(0);});
});
