import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, ChevronRight, CircleHelp, Clock3, FileSpreadsheet, FileText, FolderOpen, Gauge, ListChecks, Microscope, Plus, RotateCw, Search, Settings, SlidersHorizontal, X } from 'lucide-react';
import type { AnalysisStep, AnalysisTask, ModelNodeId, ModelProfile, RuntimeConfig, RuntimeStatus, PrdProject, RequirementDetail } from './types';
import { MaterialWorkspace } from './MaterialWorkspace';
import { ResultIssues } from './ResultIssues';
import { clarificationCounts, featureTitle, readableContext, requirementSourceRefs, sourceExcerpt, sourceHeading, sourcePosition } from './result-presentation';

const stepDefs=[['inventory','原文建账','登记原文、结构、位置与缺失材料'],['candidates','功能候选识别','按连贯原文包并行识别功能候选'],['coverage','功能候选完整性检查','独立查漏；问题定点退回候选识别'],['unify','功能清单统一','对完整候选集去重并统一边界与来源'],['details','逐功能细化','逐项整理需求、条件与待澄清内容'],['audit','完整性与忠实性检查','检查遗漏、误读与无依据新增'],['repair','局部修正','仅修正已定位的问题及受影响条目'],['delivery','交付','检查最终快照并生成 Agent 需求包']];
const modelNodes:[ModelNodeId,string,string][]=[['imageReading','图片内容读取','按需转录图片、图表和页面内容'],['featureCandidates','功能候选识别','按连贯候选内容快速识别候选'],['featureCandidateRepair','候选定点返工','根据完整性问题修订受影响候选内容'],['featureGlobal','功能清单统一','处理语义重叠和边界争议'],['featureCoverage','功能完整性检查','独立上下文检查遗漏与错归'],['detailsFast','简单功能细化','整理短小、无复杂联动的功能'],['details','复杂功能细化','处理状态、权限、依赖和复杂条件'],['audit','完整性与忠实性检查','按候选内容检查遗漏、误读和新增'],['repair','局部修正','只处理审计已定位的问题']];
const defaultNodeProfiles=(adapter:RuntimeConfig['adapter']):Record<ModelNodeId,ModelProfile>=>{const fast=adapter==='codex-oauth'?'gpt-5.6-luna':'deepseek-v4-flash',critical=adapter==='codex-oauth'?'gpt-5.6-sol':'deepseek-v4',standard=adapter==='codex-oauth'?'gpt-5.6-terra':'deepseek-v4';return{imageReading:{model:fast,reasoningEffort:'low'},featureCandidates:{model:fast,reasoningEffort:'low'},featureCandidateRepair:{model:standard,reasoningEffort:'low'},featureGlobal:{model:standard,reasoningEffort:'low'},featureCoverage:{model:critical,reasoningEffort:'low'},detailsFast:{model:fast,reasoningEffort:'low'},details:{model:standard,reasoningEffort:'low'},audit:{model:critical,reasoningEffort:'low'},repair:{model:standard,reasoningEffort:'low'}}};
const stepModelNodes:Record<string,Array<{node:ModelNodeId;label:string;purpose:string}>>={inventory:[{node:'imageReading',label:'图片转录',purpose:'仅在候选内容含图片时调用'}],candidates:[{node:'featureCandidates',label:'首次识别',purpose:'逐份候选内容提取功能候选'},{node:'featureCandidateRepair',label:'定点返工',purpose:'只修订检查发现问题的候选'}],coverage:[{node:'featureCoverage',label:'独立复查',purpose:'检查功能遗漏、错归和误分类'}],unify:[{node:'featureGlobal',label:'跨候选统一',purpose:'合并重复候选并统一功能边界'}],details:[{node:'detailsFast',label:'简单功能细化',purpose:'处理短小且无复杂联动的功能'},{node:'details',label:'复杂功能与补漏',purpose:'处理状态、权限、依赖、例外及定点补漏'}],audit:[{node:'audit',label:'独立审计',purpose:'核对遗漏、误读和无依据新增'}],repair:[{node:'repair',label:'定点修正',purpose:'只修改审计定位的受影响条目'}],delivery:[]};
const fastModelNodes=new Set<ModelNodeId>(['imageReading','featureCandidates','detailsFast']);
const reasoningLabels:Record<RuntimeConfig['reasoningEffort'],string>={default:'模型默认',low:'低',medium:'中',high:'高',xhigh:'XHigh',max:'Max',ultra:'Ultra'};
function taskNodeProfile(task:AnalysisTask,node:ModelNodeId):ModelProfile|undefined{const config=task.runtimeConfig;if(!config)return undefined;const configured=config.nodeProfiles?.[node];return{model:configured?.model??(fastModelNodes.has(node)?config.fastModel??config.model:config.model),reasoningEffort:configured?.reasoningEffort??(fastModelNodes.has(node)?config.fastReasoningEffort??'low':config.reasoningEffort)}}
function stepRuntimeItems(task:AnalysisTask,stepId:string){return(stepModelNodes[stepId]??[]).map(item=>{const profile=taskNodeProfile(task,item.node);return{...item,profile}})}
function stepDisplayNote(note:string){return note.replaceAll('来源包','候选内容')}
const names=['订单查询','订单详情','批量导出','退款申请','退款审核','发票管理','优惠计算','支付状态'];
function demoProject(id='demo',name='交易中心 3.0'):PrdProject{const requirements:RequirementDetail[]=Array.from({length:48},(_,i)=>({id:`R-${String(i+1).padStart(3,'0')}`,title:['按筛选条件返回结果','限制单次处理数量','校验字段完整性'][i%3],behavior:`${names[i%8]}场景下，系统根据状态与输入条件完成处理。`,conditions:['用户具备操作权限','数据处于允许状态'],constraints:i%3===0?['单次最多 1000 条']:[],explicitAcceptanceConditions:[],sourceUnitIds:[`S-${String(i%12+1).padStart(3,'0')}`],ruleIds:[`RL-${String(i+1).padStart(3,'0')}`],state:(i+1)%9===0?'needs-clarification':'reviewed'}));return{id,name,sourceName:`${name}产品需求文档.docx`,sourceHash:id,revision:1,importedAt:new Date().toISOString(),rawText:'',stage:'review',sourceUnits:Array.from({length:12},(_,i)=>({id:`S-${String(i+1).padStart(3,'0')}`,label:`原文单元 ${i+1}`,kind:'paragraph',excerpt:'原文中的行为、条件和边界说明。',location:`第 ${i+2} 页`,status:'processed'})),rules:requirements.map((r,i)=>({id:r.ruleIds[0],statement:r.behavior,sourceUnitIds:r.sourceUnitIds,conditions:r.conditions,kind:'behavior',status:'explicit'})),features:names.map((n,i)=>({id:`F-${String(i+1).padStart(2,'0')}`,name:n,goal:`完成${n}相关业务能力`,sourceUnitIds:[`S-${String(i+1).padStart(3,'0')}`],ruleIds:requirements.filter((_,r)=>r%8===i).flatMap(x=>x.ruleIds),requirementIds:requirements.filter((_,r)=>r%8===i).map(x=>x.id),state:'reviewed'})),requirements,clarifications:Array.from({length:5},(_,i)=>({id:`Q-${i+1}`,question:`${names[i]}的异常提示文案是什么？`,reason:'原文没有唯一取值。',affectedIds:[`R-${String((i+1)*9).padStart(3,'0')}`],state:'open'}))}}
function freshTask(project:PrdProject,index:number):AnalysisTask{const now=Date.now();return{id:`T-${String(index).padStart(4,'0')}`,project,attempt:1,status:'running',progress:0,createdAt:now,startedAt:now,steps:stepDefs.map(([id,name,note],i)=>({id,name,note,status:i===0?'running':'pending',startedAt:i===0?now:undefined}))}}
const completedProject=demoProject();const completedTask:AnalysisTask={...freshTask(completedProject,1),status:'completed',progress:100,startedAt:Date.now()-188000,completedAt:Date.now()-30000,steps:stepDefs.map(([id,name,note],i)=>({id,name,note,status:'completed',startedAt:Date.now()-188000+i*30000,completedAt:Date.now()-188000+(i+1)*30000}))};
type Page='tasks'|'upload'|'task'|'settings';type ResultTab='summary'|'features'|'requirements'|'issues';
const statusLabel={queued:'排队中',running:'执行中',completed:'可交付','needs-attention':'平台整理未完成',failed:'执行失败'};
function elapsed(start?:number,end?:number,now=Date.now()){if(start===undefined)return '—';const seconds=Math.max(0,Math.floor(((end??now)-start)/1000));return seconds<60?`${seconds} 秒`:`${Math.floor(seconds/60)} 分 ${seconds%60} 秒`}
export function runtimeTiming(task:AnalysisTask){const calls=[...(task.runtimeMetrics??[])].sort((a,b)=>a.startedAt-b.startedAt),attempts=new Map<number,{start:number;end:number}>();let active=0,end=0;for(const call of calls){if(call.startedAt>end)active+=Math.max(0,call.completedAt-call.startedAt);else if(call.completedAt>end)active+=call.completedAt-end;end=Math.max(end,call.completedAt);const match=call.sessionId.match(/-a(\d+)-/),attempt=match?Number(match[1]):0,current=attempts.get(attempt);attempts.set(attempt,{start:Math.min(current?.start??call.startedAt,call.startedAt),end:Math.max(current?.end??call.completedAt,call.completedAt)})}const ranges=[...attempts.entries()].sort((a,b)=>a[0]-b[0]).map(([,range])=>range);let retryWait=0;for(let i=1;i<ranges.length;i++)retryWait+=Math.max(0,ranges[i].start-ranges[i-1].end);return{active,retryWait}}

export function App(){const[tasks,setTasks]=useState<AnalysisTask[]>([completedTask]);const[page,setPage]=useState<Page>('tasks');const[activeId,setActiveId]=useState(completedTask.id);const[now,setNow]=useState(Date.now());const[harness,setHarness]=useState<RuntimeStatus>({available:false,reason:'正在检测'});
 useEffect(()=>{if(!window.prdApp)return;void Promise.all([window.prdApp.inspectRuntime(),window.prdApp.loadAnalysisTasks()]).then(([runtime,saved])=>{setHarness(runtime);setTasks(saved);if(saved[0])setActiveId(saved[0].id)});return window.prdApp.onAnalysisTaskUpdate(updated=>setTasks(current=>[updated,...current.filter(task=>task.id!==updated.id)]))},[]);useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);
 useEffect(()=>{if(window.prdApp)return;const id=setInterval(()=>setTasks(current=>current.map(task=>advance(task))),1000);return()=>clearInterval(id)},[]);
 const active=tasks.find(t=>t.id===activeId);
 function openTask(id:string){setActiveId(id);setPage('task')}
 return <main className="platform"><TopBar page={page} setPage={setPage} harness={harness}/>{page==='tasks'?<TaskCenter tasks={tasks} now={now} onOpen={openTask} onNew={()=>setPage('upload')}/>:page==='upload'?<MaterialWorkspace onStart={async p=>{const task=await window.prdApp.startAnalysis(p);setTasks(c=>[task,...c.filter(x=>x.id!==task.id)]);setActiveId(task.id);setPage('task')}} onBack={()=>setPage('tasks')}/>:page==='settings'?<RuntimeSettings status={harness} onStatus={setHarness}/>:active?<TaskPage task={active} now={now} onBack={()=>setPage('tasks')}/>:null}</main>}
function advance(task:AnalysisTask):AnalysisTask{if(task.status!=='running')return task;const progress=Math.min(100,task.progress+2);const stage=Math.min(4,Math.floor(progress/20));const now=Date.now();const steps=task.steps.map((s,i):AnalysisStep=>i<stage?{...s,status:'completed',completedAt:s.completedAt??now}:i===stage&&progress<100?{...s,status:'running',startedAt:s.startedAt??now}:{...s,status:i===stage?'completed':'pending',completedAt:i===stage?now:s.completedAt});if(progress===100){void window.prdApp?.prepareResult(task.project);return{...task,progress,status:'completed',completedAt:now,steps}}return{...task,progress,steps}}

function TopBar({page,setPage,harness}:{page:Page;setPage:(p:Page)=>void;harness:RuntimeStatus}){const name=harness.adapter==='dsh'?'DeepSeek Harness':'Codex CLI';const label=harness.routeReady?`${name} ${harness.version}`:harness.available?`${name} 已安装`:'Runtime 未连接';return <header className="platform-bar"><button className="logo" onClick={()=>setPage('tasks')}><Microscope/><strong>需求细化平台</strong></button><nav><button className={page!=='settings'?'active':''} onClick={()=>setPage('tasks')}><ListChecks/>任务</button><button className={page==='settings'?'active':''} onClick={()=>setPage('settings')}><Settings/>Runtime 配置</button></nav><div className={harness.routeReady?'runtime ready':'runtime'}><i/><span>{label}</span></div></header>}
function TaskCenter({tasks,now,onOpen,onNew}:{tasks:AnalysisTask[];now:number;onOpen:(id:string)=>void;onNew:()=>void}){const running=tasks.filter(t=>t.status==='running').length;return <div className="page task-center"><div className="page-title"><div><span>任务中心</span><h1>需求分析任务</h1><p>查看所有 PRD 的处理状态；运行中的任务彼此独立，可并行执行。</p></div><button className="primary" onClick={onNew}><Plus/>新建任务</button></div><div className="task-metrics"><Metric label="全部任务" value={tasks.length}/><Metric label="并行执行中" value={running}/><Metric label="已完成" value={tasks.filter(t=>t.status==='completed').length}/><Metric label="需要处理" value={tasks.filter(t=>t.status==='failed').length}/></div><section className="collection task-collection"><div className="collection-head"><h2>任务列表 <b>{tasks.length}</b></h2><span>{running>0?`当前 ${running} 个任务正在执行`:'当前没有执行中的任务'}</span></div><div className="task-table"><div className="thead"><span>任务</span><span>状态</span><span>当前阶段</span><span>进度</span><span>墙钟耗时</span><span>创建时间</span><span aria-hidden="true"/></div>{tasks.length===0?<div className="task-empty"><ListChecks/><strong>还没有需求分析任务</strong><span>选择一份主 PRD，开始第一次需求细化。</span><button className="secondary" onClick={onNew}>新建任务</button></div>:tasks.map(t=>{const step=t.steps.find(s=>s.status==='running')??t.steps.at(-1);return <button className="task-row" key={t.id} onClick={()=>onOpen(t.id)} aria-label={`打开任务 ${t.id}：${t.project.name}`}><span className="task-identity"><span className="task-primary-line"><code>{t.id}</code><strong>{t.project.name}</strong></span><small><FileText aria-hidden="true"/>{t.project.sourceName}</small></span><em className={`task-status ${t.status}`}>{statusLabel[t.status]}</em><span className="task-stage">{step?.name}</span><span className="mini-progress" role="progressbar" aria-label={`${t.project.name}进度`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={t.progress}><i style={{width:`${t.progress}%`}}/><b>{t.progress}%</b></span><span className="task-time">{elapsed(t.startedAt,t.completedAt,now)}</span><span className="task-time">{new Date(t.createdAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</span><span className="task-open" aria-hidden="true"><ChevronRight/></span></button>})}</div></section></div>}
function Metric({label,value}:{label:string;value:number}){return <div><span>{label}</span><strong>{value}</strong></div>}
function TaskPage({task,now,onBack}:{task:AnalysisTask;now:number;onBack:()=>void}){const[tab,setTab]=useState<ResultTab>('summary');const[detail,setDetail]=useState<RequirementDetail>();const[featureFilter,setFeatureFilter]=useState<string>();const attention=task.status==='needs-attention';return <div className="page"><button className="back" onClick={onBack}>返回任务中心</button><div className="task-title"><div><code>{task.id}</code><h1>{task.project.name}</h1><p>{task.project.sourceName}</p></div><div><em className={`task-status ${task.status}`}>{statusLabel[task.status]}</em>{(task.status==='completed'||attention)&&<button className="secondary" onClick={()=>window.prdApp?.openResultDirectory(task.id)}><FolderOpen/>打开结果目录</button>}{task.status==='running'&&<button className="secondary" onClick={()=>window.prdApp?.cancelAnalysis(task.id)}>取消任务</button>}{(task.status==='failed'||attention)&&<button className="primary" onClick={()=>window.prdApp?.retryAnalysis(task.id)}><RotateCw/>{attention?'继续平台整理':'从检查点重试'}</button>}</div></div><RuntimeCost task={task}/>{task.status==='running'||task.status==='queued'?<Progress task={task} now={now}/>:task.status==='failed'?<section className="audit"><AlertTriangle/><h2>任务执行失败</h2><p>{task.error}</p></section>:<>{attention&&<section className="audit"><AlertTriangle/><h2>平台整理未完成</h2><p>{task.error}</p></section>}<Results project={task.project} tab={tab} setTab={setTab} featureFilter={featureFilter} setFeatureFilter={setFeatureFilter} onDetail={setDetail}/></>} {detail&&<Drawer project={task.project} item={detail} onClose={()=>setDetail(undefined)}/>}</div>}
function metricNode(id:string){if(id.includes('-asset-'))return'图片读取';if(id.includes('-candidate-'))return'功能候选识别';if(id.includes('-unify'))return'功能清单统一';if(id.includes('-coverage-'))return'功能完整性检查';if(id.includes('-details-'))return'逐功能细化';if(id.includes('-audit-'))return'完整性与忠实性检查';if(id.includes('-repair-'))return'局部修正';return'其他'}
export function RuntimeCost({task}:{task:AnalysisTask}){const calls=task.runtimeMetrics??[];if(!calls.length)return null;const input=calls.reduce((sum,item)=>sum+(item.inputTokens??0),0),cached=calls.reduce((sum,item)=>sum+(item.cachedInputTokens??0),0),output=calls.reduce((sum,item)=>sum+(item.outputTokens??0),0),measured=calls.some(item=>item.inputTokens!==undefined||item.outputTokens!==undefined),timing=runtimeTiming(task),wall=task.startedAt===undefined?0:(task.completedAt??Date.now())-task.startedAt,groups=Object.values(calls.reduce<Record<string,{name:string;model:string;reasoningEffort:RuntimeConfig['reasoningEffort'];calls:number;duration:number;input:number;cached:number;output:number}>>((all,item)=>{const name=metricNode(item.sessionId),key=`${name}\u0000${item.model}\u0000${item.reasoningEffort}`,entry=all[key]??={name,model:item.model,reasoningEffort:item.reasoningEffort,calls:0,duration:0,input:0,cached:0,output:0};entry.calls++;entry.duration+=item.durationMs;entry.input+=item.inputTokens??0;entry.cached+=item.cachedInputTokens??0;entry.output+=item.outputTokens??0;all[key]=entry;return all},{}));return <section className="runtime-cost-wrap"><div className="runtime-cost"><div><span>模型调用</span><strong>{calls.length}</strong></div><div><span>输入 Token</span><strong>{measured?input.toLocaleString():'Runtime 未返回'}</strong></div><div><span>缓存输入</span><strong>{measured?cached.toLocaleString():'—'}</strong></div><div><span>输出 Token</span><strong>{measured?output.toLocaleString():'—'}</strong></div><div><span>模型活跃耗时</span><strong>{elapsed(0,timing.active)}</strong></div><div><span>墙钟耗时</span><strong>{elapsed(0,wall)}</strong></div>{timing.retryWait>0&&<div><span>等待重试</span><strong>{elapsed(0,timing.retryWait)}</strong></div>}</div><details><summary>查看节点成本分布</summary><div className="runtime-cost-table"><table><thead><tr><th>节点</th><th>模型</th><th>推理深度</th><th>调用</th><th>累计耗时</th><th>输入</th><th>缓存输入</th><th>输出</th></tr></thead><tbody>{groups.map(item=><tr key={`${item.name}-${item.model}-${item.reasoningEffort}`}><td>{item.name}</td><td><code>{item.model}</code></td><td>{reasoningLabels[item.reasoningEffort]}</td><td>{item.calls}</td><td>{elapsed(0,item.duration)}</td><td>{measured?item.input.toLocaleString():'—'}</td><td>{measured?item.cached.toLocaleString():'—'}</td><td>{measured?item.output.toLocaleString():'—'}</td></tr>)}</tbody></table></div></details></section>}
export function Progress({task,now}:{task:AnalysisTask;now:number}){return <section className="progress-card"><header><div><span>正在执行</span><h2>Runtime 正在分析需求</h2></div><strong>{task.progress}%</strong></header><div className="progress-track"><i style={{width:`${task.progress}%`}}/></div><div className="step-list">{task.steps.map((s,i)=>{const current=s.status==='running'&&s.startedAt?now-s.startedAt:0,total=(s.durationMs??0)+current,items=stepRuntimeItems(task,s.id);return <div className={`step ${s.status}`} key={s.id}><i>{s.status==='completed'?<CheckCircle2/>:i+1}</i><div><strong>{s.name}</strong><small>{stepDisplayNote(s.note)}{(s.runs??0)>0?`；累计业务调用 ${s.runs} 次`:''}</small><div className="step-runtime">{items.length?items.map(item=><small key={item.node}><b>{item.label}</b><span>{item.purpose}</span><code>{item.profile?.model??'模型配置未记录'}</code><em>{item.profile?`推理 ${reasoningLabels[item.profile.reasoningEffort]}`:'—'}</em></small>):<small className="deterministic"><b>执行方式</b><span>由确定性脚本处理</span><em>不使用模型</em></small>}</div></div><span>{s.status==='running'?`已执行 ${elapsed(0,total)}`:s.status==='completed'?`累计 ${elapsed(0,total)}`:'等待执行'}</span></div>})}</div><footer><Clock3/>任务墙钟时长 {elapsed(task.startedAt,undefined,now)}</footer></section>}

function Results({project,tab,setTab,featureFilter,setFeatureFilter,onDetail}:{project:PrdProject;tab:ResultTab;setTab:(t:ResultTab)=>void;featureFilter?:string;setFeatureFilter:(id?:string)=>void;onDetail:(r:RequirementDetail)=>void}){const counts=clarificationCounts(project),tabs:[ResultTab,string][]=[['summary','概览'],['features','功能与需求'],['requirements','全部需求'],['issues','待处理事项']];return <><nav className="result-tabs">{tabs.map(([id,label])=><button className={tab===id?'active':''} onClick={()=>{setTab(id);if(id==='requirements')setFeatureFilter(undefined)}} key={id}>{label}{id==='issues'&&<b>{counts.blocking+counts.suggestion+counts.ignorable+counts.platform}</b>}</button>)}</nav>{tab==='summary'?<Summary p={project} setTab={setTab}/>:tab==='features'?<FeatureList p={project} onNext={id=>{setFeatureFilter(id);setTab('requirements')}}/>:tab==='requirements'?<RequirementList p={project} featureId={featureFilter} onClearFeature={()=>setFeatureFilter(undefined)} onDetail={onDetail}/>:<ResultIssues project={project}/>}</>}
function Summary({p,setTab}:{p:PrdProject;setTab:(t:ResultTab)=>void}){const pending=p.sourceUnits.filter(s=>s.status!=='processed').length,counts=clarificationCounts(p),state=p.delivery?.state??'unchecked',deliveryLabel=state==='ready'?'需求检查通过，可以交付':state==='blocked'?'暂不能交付':'需求检查尚未完成',blocking=counts.blocking+counts.platform;return <div className="summary"><div className="result-metrics"><Metric label="阻塞" value={blocking}/><Metric label="建议" value={counts.suggestion}/><Metric label="可忽略" value={counts.ignorable}/><Metric label="需求明细" value={p.requirements.length}/></div><div className="summary-columns"><section className={`panel delivery-summary ${state}`}><span className="summary-kicker">当前交付状态</span><h2>{deliveryLabel}</h2><p>{state==='ready'?`必要检查已完成。${counts.suggestion||counts.ignorable?`另有 ${counts.suggestion} 项建议、${counts.ignorable} 项可忽略事项，不影响交付。`: '当前没有待处理事项。'}`:state==='blocked'?`${counts.blocking} 项业务澄清、${counts.platform} 项平台整理问题需要先处理。`:'检查没有完整结论，当前结果仅供查看。'}</p>{blocking>0&&<button className="primary" onClick={()=>setTab('issues')}>处理阻塞事项</button>}{blocking===0&&(counts.suggestion+counts.ignorable)>0&&<button className="secondary" onClick={()=>setTab('issues')}>查看建议与可忽略事项</button>}<div className="check"><span><strong>材料处理：{pending===0?'已完成':`${pending} 项未完成`}</strong><small>共读取 {p.sourceUnits.length} 处原文；内部来源编号仅保留在机器追溯数据中。</small></span></div></section><section className="panel workbook"><FileSpreadsheet/><h2>{state==='ready'?'Agent 需求交付包已生成':'整理草稿已生成'}</h2><p>JSON、逐功能 Markdown 与 Excel 来自同一需求快照，待处理事项在三个产物中使用相同级别和状态。</p><button className="text-action" onClick={()=>setTab('features')}>查看功能与需求</button><small>需求检查通过不表示已在真实业务仓库验证实施结果。</small></section></div></div>}
function FeatureList({p,onNext}:{p:PrdProject;onNext:(id:string)=>void}){return <Collection title="功能与需求" count={p.features.length}><div className="data-table features"><div className="thead"><span>功能名称</span><span>原文位置</span><span>需求</span></div>{p.features.map(f=>{const source=p.sourceUnits.find(item=>item.id===f.sourceUnitIds[0]);return <button className="data-row" key={f.id} onClick={()=>onNext(f.id)}><span><strong>{featureTitle(p,f)}</strong><small>{f.id}</small></span><span>{source?sourcePosition(source):'来源待定位'}</span><b>{f.requirementIds.length}</b></button>})}</div></Collection>}
function RequirementList({p,featureId,onClearFeature,onDetail}:{p:PrdProject;featureId?:string;onClearFeature:()=>void;onDetail:(r:RequirementDetail)=>void}){const[q,setQ]=useState('');const[page,setPage]=useState(1);const feature=p.features.find(item=>item.id===featureId),allowed=feature?new Set(feature.requirementIds):undefined;const rows=useMemo(()=>p.requirements.filter(r=>(!allowed||allowed.has(r.id))&&`${r.id}${r.title}${r.behavior}${r.conditions.join()}${r.constraints.join()}`.includes(q)),[p,q,featureId]);const pageSize=50,pages=Math.max(1,Math.ceil(rows.length/pageSize)),visible=rows.slice((page-1)*pageSize,page*pageSize);useEffect(()=>setPage(1),[q,featureId]);return <Collection title={feature?`需求明细 · ${featureTitle(p,feature)}`:'需求明细'} count={rows.length}><div className="collection-tools">{feature&&<button className="text-action" onClick={onClearFeature}>查看全部需求明细</button>}<label className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} aria-label="搜索需求明细" placeholder="搜索编号、行为或条件"/>{q&&<button aria-label="清空搜索" onClick={e=>{setQ('');e.currentTarget.parentElement?.querySelector('input')?.focus()}}><X/></button>}</label></div><div className="data-table requirements"><div className="thead"><span>编号</span><span>需求明细</span><span>条件</span><span>状态</span></div>{visible.length===0&&<p className="empty-result">没有匹配的需求明细，请调整搜索条件。</p>}{visible.map(r=><button className="data-row" key={r.id} onClick={()=>onDetail(r)}><code>{r.id}</code><span><strong>{r.title}</strong><small>{r.behavior}</small></span><b>{r.conditions.length+r.constraints.length}</b><b>{r.state==='needs-clarification'?'有待澄清项':r.state==='reviewed'?'检查通过':'尚未检查'}</b></button>)}</div>{pages>1&&<footer className="pagination"><span>第 {page}/{pages} 页 · 每页最多 {pageSize} 项</span><div><button className="secondary" disabled={page===1} onClick={()=>setPage(value=>value-1)}>上一页</button><button className="secondary" disabled={page===pages} onClick={()=>setPage(value=>value+1)}>下一页</button></div></footer>}</Collection>}
function Collection({title,count,children}:{title:string;count:number;children:React.ReactNode}){return <section className="collection result"><div className="collection-head"><h2>{title} <b>{count}</b></h2></div>{children}</section>}
function Drawer({project,item,onClose}:{project:PrdProject;item:RequirementDetail;onClose:()=>void}){useEffect(()=>{const listener=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener)},[onClose]);return <aside className="drawer" aria-label="需求明细"><header><div><code>{item.id}</code><h2>{item.title}</h2><small>{item.state==='needs-clarification'?'有待澄清项':item.state==='reviewed'?'检查通过':'尚未检查'}</small></div><button onClick={onClose} aria-label="关闭"><X/></button></header><div><h3>具体要求</h3><p>{item.behavior}</p><h3>条件与限制</h3>{[...item.conditions,...item.constraints].map(x=><p className="rule" key={x}>{x}</p>)}{item.explicitAcceptanceConditions.length>0&&<><h3>PRD 原文明示验收条件</h3>{item.explicitAcceptanceConditions.map(x=><p className="rule" key={x}>{x}</p>)}</>}<h3>原文及位置</h3>{requirementSourceRefs(item).map((ref,index)=>{const source=project.sourceUnits.find(s=>s.id===ref.sourceUnitId);return source?<section className="source-card" key={`${ref.sourceUnitId}-${ref.start??'all'}-${index}`}><strong>{sourceHeading(source)}</strong><small>{sourcePosition(source)}</small>{readableContext(source.context)&&<p>{readableContext(source.context)}</p>}<p className="source-excerpt">{sourceExcerpt(source,ref)}</p></section>:<p key={`${ref.sourceUnitId}-${index}`}>来源待定位</p>})}</div></aside>}

function RuntimeSettings({status,onStatus}:{status:RuntimeStatus;onStatus:(s:RuntimeStatus)=>void}) {
  const [config,setConfig]=useState<RuntimeConfig>({adapter:'codex-oauth',provider:'openai-codex',fastModel:'gpt-5.6-luna',fastReasoningEffort:'low',model:'gpt-5.6-terra',reasoningEffort:'low',nodeProfiles:defaultNodeProfiles('codex-oauth'),maxParallel:5,maxNodeParallel:10});
  const [saved,setSaved]=useState(false);
  const [checking,setChecking]=useState<'status'|'connection'|null>(null);
  const [checkedAt,setCheckedAt]=useState<string>();
  const [checkError,setCheckError]=useState('');
  const [lastCheck,setLastCheck]=useState(false);
  useEffect(()=>{window.prdApp?.loadRuntimeConfig().then(setConfig)},[]);
  async function save(){await window.prdApp?.saveRuntimeConfig(config);setSaved(true)}
  async function check(connection=false){if(checking||!window.prdApp)return;setLastCheck(connection);setChecking(connection?'connection':'status');setCheckError('');try{const result=await (connection?window.prdApp.testRuntime(config):window.prdApp.inspectRuntime(config));onStatus(result);setCheckedAt(new Date().toLocaleTimeString('zh-CN'));if(result.reason||result.authStatus==='error')setCheckError(result.reason??'认证状态读取失败，请重试')}catch{setCheckError('未能取得检查结果，请重试；下方保留上次结果。')}finally{setChecking(null)}}
  function changeAdapter(adapter:RuntimeConfig['adapter']){setConfig(adapter==='codex-oauth'?{...config,adapter,provider:'openai-codex',fastModel:'gpt-5.6-luna',fastReasoningEffort:'low',model:'gpt-5.6-terra',reasoningEffort:'low',nodeProfiles:defaultNodeProfiles(adapter),apiKey:undefined}:{...config,adapter,provider:'deepseek-official',fastModel:'deepseek-v4-flash',fastReasoningEffort:'low',model:'deepseek-v4',reasoningEffort:'low',nodeProfiles:defaultNodeProfiles(adapter)})}
  function updateNode(node:ModelNodeId,patch:Partial<ModelProfile>){const fallback=defaultNodeProfiles(config.adapter)[node],current=config.nodeProfiles?.[node]??fallback;setConfig({...config,nodeProfiles:{...config.nodeProfiles,[node]:{...current,...patch}}})}
  const state=status.routeReady?'已连接':status.available?'已安装，待验证':'未连接';
  const codexModels=['gpt-6-astra','gpt-5.6-sol','gpt-5.6-terra','gpt-5.6-luna','gpt-5.5','gpt-5.3-codex-spark'];
  return <div className="page settings-page"><div className="page-title"><div><span>运行时设置</span><h1>统一 Runtime 配置</h1><p>选择执行适配器、模型与推理深度；新任务会固化当前配置。</p></div></div><section className="settings-card"><header><SlidersHorizontal/><div><h2>模型执行配置</h2><p>{config.adapter==='codex-oauth'?'官方 Codex CLI · 复用 CLI 认证':'DeepSeek Harness · SDK JSON-RPC'}</p></div><em className={status.routeReady?'connected':''}>{state}</em></header><div className="form-grid">
    <label><span>Runtime 适配器</span><select disabled={!!checking} value={config.adapter} onChange={e=>changeAdapter(e.target.value as RuntimeConfig['adapter'])}><option value="codex-oauth">Codex CLI</option><option value="dsh">DeepSeek Harness</option></select><small>平台调度协议保持一致，底层执行器可切换</small></label>
    {config.adapter==='dsh'&&<label><span>Provider</span><input value={config.provider} onChange={e=>setConfig({...config,provider:e.target.value})}/><small>Harness 中注册的提供方标识</small></label>}
    <div className="node-profiles"><div className="node-profile-head"><strong>节点模型策略</strong><span>模型</span><span>推理深度</span></div>{modelNodes.map(([id,name,note])=>{const profile=config.nodeProfiles?.[id]??defaultNodeProfiles(config.adapter)[id];return <div className="node-profile-row" key={id}><div><strong>{name}</strong><small>{note}</small></div>{config.adapter==='codex-oauth'?<select aria-label={`${name}模型`} value={profile.model} onChange={e=>updateNode(id,{model:e.target.value})}>{codexModels.map(model=><option key={model} value={model}>{model}</option>)}</select>:<input aria-label={`${name}模型`} value={profile.model} onChange={e=>updateNode(id,{model:e.target.value})}/>}<select aria-label={`${name}推理深度`} value={profile.reasoningEffort} onChange={e=>updateNode(id,{reasoningEffort:e.target.value as RuntimeConfig['reasoningEffort']})}><option value="default">模型默认</option><option value="low">低</option><option value="medium">中</option><option value="high">高</option>{config.adapter==='codex-oauth'&&<><option value="xhigh">XHigh</option><option value="max">Max</option><option value="ultra">Ultra</option></>}</select></div>})}</div>
    {config.adapter==='dsh'&&config.provider==='deepseek-official'&&<label><span>DeepSeek API Key</span><input type="password" autoComplete="off" value={config.apiKey??''} onChange={e=>setConfig({...config,apiKey:e.target.value})} placeholder="输入后由系统加密保存"/><small>仅注入 Harness 子进程</small></label>}
    <label><span>最大并行任务</span><input type="number" min="1" max="8" value={config.maxParallel} onChange={e=>setConfig({...config,maxParallel:Number(e.target.value)})}/><small>超过数量的任务进入排队</small></label>
    <label><span>单任务节点并发</span><input type="number" min="1" max="10" value={config.maxNodeParallel??10} onChange={e=>setConfig({...config,maxNodeParallel:Number(e.target.value)})}/><small>逐功能细化与审计的并发上限</small></label>
  </div><footer><button className="secondary runtime-check-button" aria-busy={checking==='status'} disabled={!!checking} onClick={()=>check()}><RotateCw className={checking==='status'?'runtime-spinner':''}/>{checking==='status'?'刷新中':'刷新状态'}</button><button className="secondary runtime-check-button" aria-busy={checking==='connection'} disabled={!!checking} onClick={()=>check(true)}><RotateCw className={checking==='connection'?'runtime-spinner':''}/>{checking==='connection'?'连接检测中':'检测模型连接'}</button><button className="primary" onClick={save}>保存配置</button>{saved&&<span>已保存</span>}</footer></section><section className="runtime-info"><h2>运行时信息</h2><div className={`runtime-feedback ${checkError?'has-error':''}`} role="status" aria-live="polite"><div><strong>{checking?checking==='status'?'正在读取运行时状态':'正在验证模型连接':checkError?'检查未完成':checkedAt?'检查完成':'运行时检查'}</strong><span>{checking?checking==='status'?'读取安装版本与认证状态，通常几秒内完成。':'依次验证当前配置的节点模型，请稍候。':checkError|| (checkedAt?`更新于 ${checkedAt}`:'刷新状态不调用模型；模型连接需单独检测。')}</span></div>{checking&&<RotateCw className="runtime-spinner" aria-hidden="true"/>}{!checking&&checkError&&<button className="secondary" onClick={()=>check(lastCheck)}>重试</button>}</div><dl><div><dt>适配器</dt><dd>{status.adapter==='codex-oauth'?'Codex CLI':status.adapter==='dsh'?'DeepSeek Harness':'—'}</dd></div><div><dt>状态</dt><dd>{state}</dd></div><div><dt>版本</dt><dd>{checking==='status'?<span className="runtime-pending">读取版本中</span>:status.version??'—'}</dd></div><div><dt>可执行文件</dt><dd>{status.launcher??status.reason??'—'}</dd></div>{status.adapter==='codex-oauth'&&<div><dt>认证状态</dt><dd>{checking==='status'?<span className="runtime-pending">读取认证状态中</span>:status.authStatus==='authenticated'?'已登录':status.authStatus==='unauthenticated'?'未登录，请在终端运行 Codex CLI 的 login 命令':status.authStatus==='error'?'检查失败，请刷新重试':'尚未检查'}</dd></div>}<div><dt>模型连接</dt><dd>{checking==='connection'?<span className="runtime-pending">等待模型响应</span>:status.routeReady===true?'可用':status.routeReady===false?'检测失败':'尚未检测'}</dd></div></dl></section></div>
}





